### ISSUE TITLE
Create Training Dataset

### ISSUE THREAD

**Issue by hphnngcquan** [chenhonghua/RePCD-Net#2]
Hi @chenhonghua,

Thank you for your good work.

I am starting to investigate your paper and code.
However, I have difficulties in producing training dataset.
Could you please provide me with the call flow for creating training dataset? I would very appreciate it.

BRs,

**Comment by chenhonghua** [comment]
Hi, @hphnngcquan 
Thanks for your interest in our work.
However, this project has been a long time.
Please refer to our paper and [modelnet_data_prep.py](https://github.com/chenhonghua/RePCD-Net/tree/main/codes/utils) for more details.

**Comment by hphnngcquan** [comment]
Hi @chenhonghua 
Thank you for your response.
Maybe i have not made it clear for you.
I would like to understand your idea of the .h5 file with the following format from [this](https://github.com/chenhonghua/RePCD-Net/blob/main/codes/data_provider.py):

> center=np.array(f['center'])[:,:num_center,:]
    input = np.array(f['noise'])[:,:num_point,:]
    gt = np.array(f['noise_gt'])[:,:num_center*2,:3]
    gt2	= np.array(f['noise_gt'])[:,:num_point,:3]
    weight = np.array(f['weight'])[:,:num_point]

Which section of the paper or which segment of code can i refer to understand the format.
