### ISSUE TITLE
如何训练？

### ISSUE THREAD

**Issue by NiuYingchun** [chenhonghua/RePCD-Net#5]
感谢您做出如此优秀的工作，我有一些简单的疑惑，希望能得到你们的解答。1. 能提供一下代码运行环境所需的tensorflow版本号吗；2. 能提供更详细的训练过程介绍与训练集吗。非常期待您的回复。

**Comment by chenhonghua** [comment]
This repository is based on Tensorflow and the TF operators from PointNet++. Therefore, you need to install tensorflow and compile the TF operators. 

For installing tensorflow, please follow the official instructions in [here](https://www.tensorflow.org/install/install_linux). The code is tested under TF1.13 (higher version should also work) and Python 3.5 on Ubuntu 16.04.

For the training dataset, you can download the training dataset `train_4000_normal_scale_label_weight_61_6.h5` from [here](https://drive.google.com/drive/folders/1xRWZ4eCGGdwQUOMZxIIC8EYZd4tDalWD?usp=sharing). Then put it in the folder `../h5_data`.

**Comment by NiuYingchun** [comment]
Thank you.
